name: 'Github Release Changelog Generator'
author: 'Kenny Wong'
description: 'Returns the commit difference count between two git references.'
inputs:
  token:
    description: 'Your GITHUB_TOKEN'
    default: ${{ github.token }}
    required: false
  filter:
    description: 'Regular expression filtering'
    default: ''
    required: false
  filter-author:
    description: 'Regular expression filtering'
    default: ''
    required: false
  head-ref:
    description: 'The name of the head reference'
    default: ''
    required: false
  gh-pages:
    description: 'Specify the branch name to get the hash from'
    default: 'gh-pages'
    required: false
  base-ref:
    description: 'The name of the base reference'
    default: ''
    required: false
  original-markdown:
    description: 'Output clean markdown content.'
    default: 'true'
    required: false
  path:
    description: 'Only commits containing this file path will be returned..'
    default: ''
    required: false

outputs:
  version:
    description: 'The version number of the tag created. example: 1.0.0'
  changelog:
    description: 'Markdown formatted changelog'
  compareurl:
    description: 'Comparing two branches to see what’s changed or to start a new pull request.'
  tag:
    description: 'Tag name.'
  branch:
    description: 'Branch name.'
  gh-pages-hash:
    description: 'Specify the branch name to get the hash from.'
  gh-pages-short-hash:
    description: 'Specify the branch name to get the short-hash from.'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'list'
  color: 'blue'
